addItem("plate-rudimentary-iron", "metal")
addItem("plate-rudimentary-copper", "metal")
addItem("plate-rudimentary-tin", "metal")
addItem("plate-rudimentary-lead", "metal")
addItem("bronze-plate-rudimentary", "metal")
addItem("dust-sand", "material")
addItem("dust-gravel", "material")
addItem("dust-clay", "material")
addItem("brick-clay", "material")

finalizeItems()